debug: true
env: "dev"
web:
  addr: "127.0.0.1:30050"
log:
  path: logs/webapi_example.log

mysql:
  uri: root:a1b3c3d4@tcp(172.20.57.191:3306)/test?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci
  max_pool_size: 50
  idle_pool_size: 20
  idle_timeout: 300
  max_lifetime: 1200


